### ISSUE TITLE
Bot kinda broke

### ISSUE THREAD

**Issue by Vovanm88** [ZaMaZaN4iK/npaperbot-telegram#10]
Bot starts to react on any message in chat. So It starts at 16:25(GMT +3) and when I go to the repository I ve seen that you commited.
![Screenshot_20210814-163546_Telegram](https://user-images.githubusercontent.com/81383125/129448181-7390e156-aa0b-4a49-b0e3-402b584ddc6e.jpg)

**Comment by zamazan4ik** [comment]
Yeah, it's a regression. Right now I am working on the fix. Stay tuned :)

**Comment by zamazan4ik** [comment]
Fixed. Thanks for the report!
